const width = 1280;
const height = 720;

const ITEMS = Object.freeze({
    any : -1,
    bread : 0,
    egg : 1,
    cheese : 2,
    bacon : 3,
    toast : 4,
    donut : 5,
    coffee : 6,
    lettuce : 7,
    tomato : 8,
    ham : 9,
    jelly : 10,
    peanut_butter : 11,
    muffin : 12,
    milk : 13,
    chocolate : 14,
    water : 15,
    americano : 16,
    latte : 17,
    mocha : 18,
    raw_bacon : 19,
    raw_egg : 20,
    bad_coffee : 21,
    raw_burrito : 22,
    burrito : 23,
    cookie : 24,
    croissant : 25,
    danish : 26,
    cake : 27,
    ramen_raw : 28,
    ramen_cooked : 29,
    ramen_water : 30,
    sandwich_ham_cheese : 31,
    sandwich_blt : 32,
    sandwich_breakfast : 33,
    sandwich_cheese_raw : 34,
    sandwich_cheese_cooked : 35,
    sandwich_christo_raw : 36,
    sandwich_christo_cooked : 37,
    sandwich_pbj : 38,
})
